### ISSUE TITLE
Migration Info Missing

### ISSUE THREAD

**Issue by dmk1111** [IgniteUI/igniteui-theming#198]
We're currently on package version 3.0.3 and igniteui-angular 16.1.1. When we decided to update to v17, we faced issue during build - `$map.get` error was throwing and nothing was happening. Theming package haven't been updated. Updating it to v4.4.0 fixed the issue.
There is no info about required updates (or breaking changes) inside Changelog nor at migration page: https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide

Please, add info about the required theming update.

**Comment by simeonoff** [comment]
Did you update to v17 using ng update?
