### ISSUE TITLE
Indigo: Grid Updates

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-theming#279]
- [x] - Query Builder @SisIvanova 
- [x] - Grid Summary @desig9stein 
- [x] - Grid Toolbar @desig9stein  
- [x] - Paginator @SisIvanova

**Comment by desig9stein** [comment]
I am adding all the required changes that @andiesm813 wants, just to have them as reference

GENERAL
_________________________________________________________

--grid-elevation: --ig-elevation-0
--grid-shadow: --ig-elevation-0
--drop-area-border-radius: 0


LIGHT THEME
_________________________________________________________


--grouparea-background: surface light (#F8F8FA)

--drop-area-text-color: grays.600
--drop-area-icon-color: grays.600
--drop-area-background: surface light
--drop-area-on-drop-background: grays.200

--header-text-color: grays.800
--header-background: surface light 
--header-border-color: grays.400

If there was such a thing as header cell hover:
- Header hover-text-color: grays.900
- Header hover-background: grays.200

--header-selected-background: primary.50
--header-selected-text-color: grays.900

--content-background: surface light
--content-text-color: grays.800 (i suppose this is "cell text color")

If there was such a thing as single cell hover:
- Cell text hover: grays.900
- Cell background hover: grays.200

--cell-active-border-color: primary.400
--cell-selected-background: primary.50
--cell-selected-text-color: grays.900
--cell-editing-background: grays.200
--edit-mode-color: primary.400
--cell-editing-foreground: grays.900

--cell-selected-within-background: primary.100
--cell-selected-within-text-color: grays.900

--row-even-text-color: grays.800
--row-even-background: surface light
--row-odd-text-color: grays.800
--row-odd-background: surface light
--row-border-color: grays.300

--row-hover-background: grays.200
--row-hover-text-color: grays.900

--row-selected-background: primary.50
--row-selected-text-color: grays.900

--row-selected-hover-background: primary.100
--row-selected-hover-text-color: grays.900



DARK THEME
_________________________________________________________

--grouparea-background: surface dark (#1E1F24)

--drop-area-text-color: white 60%
--drop-area-icon-color: white 60%
--drop-area-background: surface dark
--drop-area-on-drop-background: dark grays.100

--header-text-color: white 90%
--header-background: surface dark
--header-border-color: dark grays.200

If there was such a thing as header cell hover:
- Header hover-text-color: white
- Header hover-background: dark grays.100

--header-selected-background: primary.900
--header-selected-text-color: white

--content-background: surface dark
--content-text-color: white 80%

If there was such a thing as single cell hover:
- Cell text hover: white
- Cell background hover: dark grays.100

--cell-active-border-color: primary.400
--cell-selected-background: primary.900
--cell-selected-text-color: white
--cell-editing-background: dark grays.100
--edit-mode-color: primary.400
--cell-editing-foreground: white

--cell-selected-within-background: primary.700
--cell-selected-within-text-color: white

--row-even-text-color: white 80%
--row-even-background: surface dark 
--row-odd-text-color: white 80%
--row-odd-background: surface dark 
--row-border-color: dark grays.100

--row-hover-background: dark grays.100
--row-hover-text-color: white

--row-selected-background: primary.900
--row-selected-text-color: white

--row-selected-hover-background: primary.700
--row-selected-hover-text-color: white
