### ISSUE TITLE
Indigo: Update Chip Theme

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-theming#326]
Handoff - https://www.figma.com/design/S4T0JkZg3RXul3w4nVgnI3/Chips-%26-Chips-Area-in-Indigo-Handoff?node-id=1-51&node-type=canvas&t=l4xuPThcRbMeYRbc-0

**Comment by imincheva** [comment]
**Design** 
https://www.figma.com/design/dkGpSYipbp68uZ1VpRfmsJ/branch/c4cOMhpXmlMuo3d4UzlCAN/Indigo.Design-UI-Kit-for-Indigo-1.5-Workfile?m=auto&node-id=11826-110&t=r95zt72fnYpePAdL-1
