### ISSUE TITLE
Handmade color palettes throw an error with unquoted keys

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-theming#362]
Problem Summary:
When using wrapper mixins (like dark-theme()) and passing a handmade palette with unquoted keys, it causes a compilation error. However, if the keys in the palette are quoted, the error is resolved, and the mixins work as expected.

**STEPS TO REPRODUCE**

1. Create a handmade palette 
```SCSS
$handmade-palette: (
    primary: (
        50: #e6eff8,
        '50-contrast': black,
        100: #bfd7f2,
        '100-contrast': black
    ),
    secondary: (
        50: #fef7e2,
        '50-contrast': black,
        100: #fdeab7,
        '100-contrast': black
    )
    ...
);
```

2.  Use the palette in a wrapper mixin like dark-heme():
```scss
@include dark-theme(
    $palette: $handmade-palette
);
```

3. Compilation error occurs.
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/cdd6dda5-e96f-44ef-b931-8086ecdc789d">

**BEHAVIOR:**

Unquoted keys in palettes cause compilation errors.
Quoting keys resolves the issue.

**EXPECTED BEHAVIOR:**

The wrapper mixins (or theme()) should handle both quoted and unquoted keys in handmade palettes, OR
The documentation should explicitly state that palette keys must be quoted to avoid errors.

**Comment by simeonoff** [comment]
Seems this is only true for the gray color variants. Likely due to the fact that the key is interpreted as color instead of string.
