### ISSUE TITLE
Add font-locations for fonts used in default themes json export

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-theming#73]
Currently a theme specifies one or more default font-families to use but for all font families that are usually not installed on the system, any app that uses the json export also needs the location the font is loaded from, e.g.

```json
{
   fluent: {
        typeface: "'Open Sans', 'Roboto', Helvetica, Arial, sans-serif",
        font-locations: [
             "https://fonts.googleapis.com/css?family=Open-Sans:300,400,500,700",
             "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700"
        ] 
   }
}
```

**Comment by simeonoff** [comment]
As per our off-line discussion, I am closing this issue.
