### ISSUE TITLE
Package Version Number

### ISSUE THREAD

**Issue by buildmotion** [IgniteUI/igniteui-theming#83]
Please align the package version number with the actual Angular/Ignite versions that it is associated with. I am not sure what version to use for an Angular application using Nx v15.x and Angular v15.x; along with @infragistics/igniteui-angular v15.x.

> Your other products have a corresponding version number, right?

**Comment by simeonoff** [comment]
Although this will help people using the `igniteui-angular` package, I don't think it will correctly reflect the changes the theming package introduces on its own. Furthermore, having the same version number as Ignite UI for Angular will not align with either the Ignite UI for Web Components or Ignite UI for Blazor packages either. Both of them use the Ignite UI Theming package.

The Ignite UI theming package is a dependency of the Ignite UI for Angular package, so the correct version should be automatically installed.

If, for some reasone, you need to install the package manually, you can always look in the [package.json file](https://www.npmjs.com/package/igniteui-angular/v/15.1.12?activeTab=code) of Ignite UI for Angular.
